### ISSUE TITLE
owner_id problem

### ISSUE THREAD

**Issue by MaMouT514** [CbCaio/Image-Attacher#1]
Hello and thank you for this work!
I just tested and I have a problem if I attach an image to a model other than user model: I have an db integrity constraint violation error because no "owner_id" available.
Would you have a complete example of the use other than on user model?
Thank you!

**Comment by MaMouT514** [comment]
I've just understand my problem..
I try to do this in my model :
public function setImageAttribute($image)
{
        if(is_object($image) && $image->isValid()){
            $this->addImage($image);
        }
}
But on creation, my model have no id at this time (no prob with update).
Is there a better way ?

**Comment by cbcaio** [comment]
Hello, 
Firstly, I'm very happy that you got interested in my package. 
I'm still finishing it, so I will ask you to please wait one or two days until you try it again. Later today I will be releasing another version with some fixes, examples and code refactoring. 

Thanks :)

**Comment by cbcaio** [comment]
Just so you have a temporary example. 

```
Route::post('/test', function(\Illuminate\Http\Request $request){

    $file = $request->file('file');
    $user = App\User::first();
    $user->addImage($file);
    return back();
}
```

**Comment by MaMouT514** [comment]
I've find a solution for my prob : 

//in my object model
public function setImageAttribute($image){
        if(is_object($image) && $image->isValid()){
            self::saved(function() use ($image){
                $this->addImage($image);
            });
        }
    }

I've used self::saved and $this->addImage($image) is executed after and all is good (save and update)!
Hope it will help!

**Comment by cbcaio** [comment]
Did you noticed that I updated a lot of stuff and changed a bit how the package works? Now it seems that everything is working properly :) But thanks anyway for posting your solution

**Comment by MaMouT514** [comment]
Ok... I haven't notice in fact ;)
But if you want to use uploads in models setXXXXAttribute functions, my solution work!
My problem was a misusing problem but nothing to say to your work except : THANKS!
