### ISSUE TITLE
Files are not being deleted when owner of the relationship is deleted

### ISSUE THREAD

**Issue by cbcaio** [CbCaio/Image-Attacher#2]
This issue only imply in deleting old files manually. However, it needs to / will be fixed soon. 

I'm open to suggestions concerning a solution to this.

:)

**Comment by MaMouT514** [comment]
Maybe add this in the trait HasImage : 

public static function boot(){
    parent::boot();
    static::deleting(function($image){
        if ($image->hasImage()) {
            $image->deleteImage();
        }
        return true;
    });
}

**Comment by cbcaio** [comment]
Thanks for you help,
this issue has already been resolved on the last update.
